name: root

channels:
  - conda-forge

dependencies:
  - htop
  - nano>=2.4.1
  - requests
  - curl
  - xz
  - pip:
    - keras
    - mwapi
    - wikipedia
    - Theano
    - pywikibot
    - docopt
    - getorg
    - tweepy
